WHITESPACE = _{ " " }

path  = { (!opts ~ ANY)* }
prog = { path }
opts = _{ debug | help | file | kvlist }
options = _{ SOI ~ prog ~ opts*? ~ EOI }

debug = { ("--debug" | "-d") }
help  = { ("--help"  | "-h") }
file  = { ("--file"  | "-f") ~ "="? ~ path }

char = { ASCII_ALPHANUMERIC | "." | "_" | "/" }
name = { char+ }
value = { char* }

kvpair = @{ name ~ "=" ~ value }
kvlist = { "--kvlist" ~ kvpair+ }
